// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjuuliodljznleoklgcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqdXVsaW9kbGp6bmxlb2tsZ2N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxODc0NTYsImV4cCI6MjA2ODc2MzQ1Nn0.cNUJTxKfXr5TWSIlHzXrFVgJ_hKAs2LM86wTefCIorM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});